#!/bin/sh
# The shebang line is for use as a stand-alone script
# vim: set ft=bash:

randsleep () {  # delete this line to make a stand-alone script
	if (( $# == 0 )); then
		echo "Usage: randsleep [min=1] max" >&2
		return 1
	elif (( $# == 2 )); then
		local min=$1 max=$2
	else
		local min=1 max=$1
	fi
	if (( max < min )); then
		(( max = max + min ))
		(( min = max - min ))
		(( max = max - min ))
	fi
	(( diff = max - min))
	command sleep $(( $RANDOM % ( diff + 1) + min ))
}  # delete this line to make a stand-alone script
